### PR TITLE
remove types related to deprecated EthPM

### PR DESCRIPTION
**Pull request by reedsa**
### What was wrong?

Re-removal of EthPM types, done in https://github.com/ethereum/eth-typing/pull/60 but was reverted in https://github.com/ethereum/eth-typing/pull/64.

### How was it fixed?

Removal of types, preserving `URI` for use elsewhere.

This change will require a `major` release version.

### Todo:

- [X] Clean up commit history

- [X] Add or update documentation related to these changes

- [X] Add entry to the [release notes](https://github.com/ethereum/eth-typing/blob/main/newsfragments/README.md)

#### Cute Animal Picture

Screen Shot 2024-04-16 at 4 36 37 PM

### CODE REVIEW

**Review by fselmo — APPROVED** [review]
lgtm 👍🏼

**Comment by fselmo** [comment]
I don't think this closes #75 though, right? We still need to remove the older `ABI` classes that are marked as `@deprecated`.

**Comment by reedsa** [comment]
@fselmo Linked to that by mistake, just got PR #82 up to close out #75.

**Review by pacrob — APPROVED** [review]
lgtm!

**Pull request merged**
